name: Mantener Supabase Activo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer peticiones a TODOS los proyectos
        run: |
          # Proyecto 1 (PaleoDB)
          curl -f -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"

          # Proyecto 2 (El nuevo)
          curl -f -X GET "${{ secrets.SUPABASE_URL_2 }}/rest/v1/" \
          -H "apikey: ${{ secrets.SUPABASE_KEY_2 }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY_2 }}"
